# Generated by Django 4.2.3 on 2023-08-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soloPro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(default=0),
        ),
    ]
