# Generated by Django 4.2.3 on 2023-08-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soloPro', '0002_pessoa_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
