# Generated by Django 4.2.3 on 2023-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soloPro', '0003_pessoa_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('proficao', models.CharField(max_length=100)),
            ],
        ),
    ]
