# Generated by Django 4.2.3 on 2023-08-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soloPro', '0005_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='atuacao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='contato',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
