# Generated by Django 4.2.3 on 2023-08-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soloPro', '0006_alter_vaga_atuacao_alter_vaga_contato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='contato',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='proficao',
            field=models.CharField(max_length=200),
        ),
    ]
